### ISSUE TITLE
Audit if new Glue Start Job API parameters are supported by Step Function

### ISSUE THREAD

**Issue by tim-pugh** [awsdocs/aws-step-functions-developer-guide#46]
https://docs.aws.amazon.com/step-functions/latest/dg/connect-glue.html

and

https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-jobs-runs.html#aws-glue-api-jobs-runs-StartJobRun

can someone audit if the step function documentation needs to be updated with already supported Glue start job API parameters, and provide examples if so?

**Comment by kirintwn** [comment]
I can confirmed that parameter `NumberOfWorkers` which is not on the Docs yet is supported (tested myself).
You can even use JsonPath with the parameter so that the value can be obtained from previous state dynamically.
I do think theoretically all the new parameters introduced by `StartJobRun` API is supported.

E.g.
```
"Glue StartJobRun": {
      "Type": "Task",
      "Resource": "arn:aws:states:::glue:startJobRun.sync",
      "Parameters": {
        "JobName": "GlueJob-JTrRO5l98qMG",
        "NumberOfWorkers.$": "$.worker_num"
      },
      "Next": "ValidateOutput"
    },
``` 

And yes, the documentation for sure needs an update.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
